USE DATABASE PRISOFT_DB;
SET DATABASE_NAME = 'PRISOFT_DB';
SET SCHEMA_NAME = 'HR_STUDENT';
SET VIEW_NAME = 'EMPLOYEE_DEPT_V';
SET VIEW_DDL_SEARCH = $DATABASE_NAME||'.'||$SCHEMA_NAME||'.'||$VIEW_NAME;

SELECT 
$VIEW_DDL_SEARCH AS VIEW_TO_SEARCH,
--IFF(TABLE_TYPE='BASE TABLE',TABLE_NAME, NULL) AS BASE_TABLE,
TABLE_CATALOG,
TABLE_SCHEMA,
TABLE_NAME,
TABLE_TYPE,
-- REGEXP_COUNT(GET_DDL('VIEW',$VIEW_DDL_SEARCH),'.*'||TABLE_NAME||'.*') AS OCCURANCE
-- REGEXP_COUNT(GET_DDL('VIEW',$VIEW_DDL_SEARCH),'(^|[^a-zA-Z0-9_])'||TABLE_NAME||'([ \n)])') AS OCCURANCE
REGEXP_COUNT(GET_DDL('VIEW',$VIEW_DDL_SEARCH),'(^|[^a-zA-Z0-9_])'||TABLE_SCHEMA||'.'||TABLE_NAME||'([ \n)])') AS OCCURANCE
FROM INFORMATION_SCHEMA.TABLES
WHERE 1=1
AND TABLE_NAME != $VIEW_NAME
HAVING OCCURANCE > 0
;